# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jenny
tagline:          'always fobby & fruity'
description:      'always fobby & fruity'
url:              http://jennyshi.com

author:
  name:           'Jenny Shi'


paginate:         5
paginate_path:    "blog/page:num"
