# Dependencies
markdown: kramdown
highlighter: rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink: pretty

# Setup
title: Jenny
tagline: 'always fobby & fruity'
description: 'always fobby & fruity'
url: http://jennyshi.com

author:
  name: 'Jenny Shi'


paginate: 5
paginate_path: "blog/page:num"
